### ISSUE TITLE
Error when deploying the package

### ISSUE THREAD

**Issue by RedaBenh** [afawcett/apex-sobjectdataloader#20] opened 2016-03-19 18:16 UTC
Hi,
I try to install the package through the button "Deploy to Salesforce"
I get the error unit test error: 
```

Failures:
classes/SObjectDataLoaderTest.cls(521,87):Method does not exist or incorrect signature: [SObjectDataLoader.SerializeConfig].addToUserFieldBlackList(Map>)


```

![image](https://cloud.githubusercontent.com/assets/1609466/13900445/ae376ed4-ee06-11e5-8297-b2f286183884.png)

**Comment by afawcett** [comment] 2016-03-20 10:34
This is a duplicate of this issue https://github.com/afawcett/apex-sobjectdataloader/issues/19

**Closed by afawcett** 2016-03-20 10:34 UTC
